// <auto-generated />
using System;
using LendingPlatform.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LendingPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(LendingDbContext))]
    partial class LendingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LendingPlatform.Domain.Entities.LoanApplication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AssetValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(7)")
                        .HasDefaultValueSql("SYSUTCDATETIME()");

                    b.Property<short>("CreditScore")
                        .HasColumnType("smallint");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("LoanAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Ltv")
                        .HasColumnType("decimal(9,4)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("LoanApplications", null, t =>
                        {
                            t.HasCheckConstraint("CK_LoanApplications_AssetValue_Positive", "[AssetValue] > 0");

                            t.HasCheckConstraint("CK_LoanApplications_CreditScore_Range", "[CreditScore] BETWEEN 1 AND 999");

                            t.HasCheckConstraint("CK_LoanApplications_Decision_Valid", "[Decision] IN ('Successful', 'Declined')");

                            t.HasCheckConstraint("CK_LoanApplications_LoanAmount_Positive", "[LoanAmount] > 0");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
